parameters:
  cms.twig.namespace: ''
  cms.twig.extension: '.twig'

services:
  #  Efrogg\ContentRenderer\ModuleRenderer\:
  #    resource: '../src/Controller'
  #    tags: ['controller.service_arguments']
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Efrogg\ContentRenderer\:
    resource: '../..'
#  Efrogg\ContentRenderer\ModuleRenderer\:
#    resource: '../../ModuleRenderer'
#
#  Efrogg\ContentRenderer\Module\:
#    resource: '../../Module'

  Efrogg\ContentRenderer\ModuleRenderer\TwigNamespaceModuleRenderer:
    arguments:
      - '@twig'
      - '%cms.twig.namespace%'
      - '%cms.twig.extension%'

  Efrogg\ContentRenderer\CmsRenderer:
    calls:
      - ['setNodeProvider',['@Efrogg\ContentRenderer\NodeProvider\NodeProviderResolver']]
      - ['initConfigurator',['@Efrogg\ContentRenderer\TwigConfigurator']]

  _instanceof:
    Efrogg\ContentRenderer\ModuleRenderer\ModuleRendererInterface:
      tags: [!php/const Efrogg\ContentRenderer\Core\Resolver\ContainerTag::TAG_MODULE_RENDERER]


    Efrogg\ContentRenderer\Module\ModuleInterface:
      tags: [!php/const Efrogg\ContentRenderer\Core\Resolver\ContainerTag::TAG_MODULE]

